name: Build APK de Natupedia

on:
  push:
    branches: [ main ]

jobs:
  build_apk:
    name: Compilar y publicar APK
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: 3. Cache de Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: 4. Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'

      - name: 5. Flutter pub get
        run: flutter pub get

      - name: 6. Compilar APK release
        run: flutter build apk --release

      - name: 7. Subir APK como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
